# Generated by Django 4.2 on 2023-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='roleField',
            field=models.CharField(default='', max_length=200),
        ),
    ]
