# Generated by Django 4.2 on 2023-04-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_rename_urlfiled_post_dummyfiled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dummyFiled',
        ),
    ]
