# Generated by Django 4.2 on 2023-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_post_locationfiled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='locationFiled',
            field=models.TextField(default=''),
        ),
    ]
