# Generated by Django 4.2 on 2023-04-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_rename_locationfiled_post_locationfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='locationField',
        ),
        migrations.AddField(
            model_name='post',
            name='urlField',
            field=models.CharField(default='', max_length=200),
        ),
    ]
