# Generated by Django 4.2 on 2023-04-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='aboutCodingField',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='aboutDesignField',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='purposeField',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='targetField',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='urlFiled',
            field=models.TextField(default=''),
        ),
    ]
