# Generated by Django 4.2 on 2023-04-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_post_urlfiled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='urlFiled',
            field=models.URLField(),
        ),
    ]
