# Generated by Django 4.2 on 2023-04-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_post_urlfiled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='urlFiled',
            new_name='dummyFiled',
        ),
    ]
