# Generated by Django 4.2 on 2023-04-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_post_locationfiled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='locationFiled',
            new_name='locationField',
        ),
    ]
