# Generated by Django 4.2 on 2023-04-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_remove_post_locationfield_post_urlfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aboutCodingField',
            new_name='aboutField',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='aboutDesignField',
            new_name='skillField',
        ),
        migrations.RemoveField(
            model_name='post',
            name='purposeField',
        ),
    ]
