# Generated by Django 4.2 on 2023-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_rename_aboutcodingfield_post_aboutfield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='targetField',
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
